### ISSUE TITLE
tree-from-tags.rb "no implicit conversion of String into Integer (TypeError)"

### ISSUE THREAD

**Issue by mbroe** [dbrock/bongo#50]
Lately, when using `tree-from-tags.rb`, I have been receiving the following error:

```
/home/mitchell/.emacs.d/elpa/bongo-20171118.1842/tree-from-tags.rb:121:in `*': no implicit conversion of String into Integer (TypeError)
	from /home/mitchell/.emacs.d/elpa/bongo-20171118.1842/tree-from-tags.rb:121:in `clear'
	from /home/mitchell/.emacs.d/elpa/bongo-20171118.1842/tree-from-tags.rb:128:in `update'
	from /home/mitchell/.emacs.d/elpa/bongo-20171118.1842/tree-from-tags.rb:156:in `block in <main>'
	from /usr/lib/ruby/2.3.0/find.rb:49:in `block (2 levels) in find'
	from /usr/lib/ruby/2.3.0/find.rb:48:in `catch'
	from /usr/lib/ruby/2.3.0/find.rb:48:in `block in find'
	from /usr/lib/ruby/2.3.0/find.rb:43:in `each'
	from /usr/lib/ruby/2.3.0/find.rb:43:in `find'
	from /home/mitchell/.emacs.d/elpa/bongo-20171118.1842/tree-from-tags.rb:154:in `<main>'
```

- GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
- ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
- Debian GNU/Linux 9.4 (stretch)
- bongo 20171118.1842 (MELPA)

**Comment by mbroe** [comment]
Never mind.  I was running this from eshell, but it seems to work fine in bash.  I believe it may be getting choked up on line 101, trying to set the `COLUMNS` variable from `ENV["COLUMNS"]`.  I don't know enough about ruby (or eshell, for that matter) to troubleshoot much further, though.  Sorry for the noise.
